apiVersion: batch/v1
kind: Job
metadata:
  labels:
    run: acme-cert
  name: acme-cert
spec:
  completions: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: acme-out
          mountPath: /usr/share/nginx/html
      - image: lobodapro/acme-socat:v0.1
        name: acme
        env:
        - name: DOMAIN
          valueFrom:
            configMapKeyRef:
              name: ss-v2ray-cm
              key: domain
        - name: ACCOUNT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: ss-v2ray-cm
              key: email
        - name: ECC_SUFFIX
          value: ""
        command: ['sh', '-c', "acme.sh --issue -d $(DOMAIN) -w /acme.sh && mv /acme.sh/$(DOMAIN)_ecc /acme.sh/$(DOMAIN) && chmod a+r /acme.sh/$(DOMAIN)/$(DOMAIN).key"]
        volumeMounts:
          - name: acme-out
            mountPath: /acme.sh
      volumes:
        - name: acme-out
          hostPath:
            path: /opt/acme.sh
            type: Directory