apiVersion: v1
kind: Service
metadata:
  name: acme-cert
spec:
  ports:
  - nodePort: 30082
    port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
  selector:
    job-name: acme-cert
status:
  loadBalancer: {}